/**
 * 
 */
package ch.ivyteam.ivy.addons.filemanager.database.sql;

/**
 * @author ec
 *
 */
public class FileTagSQLQueries {
	
	public static String TABLENAMESPACE_PLACEHOLDER ="TABLENAMESPACE";
	
	/**
	 * SELECT * FROM --TABLENAMESPACE_PLACEHOLDER-- WHERE id = ?
	 */
	public static String SELECT_FILETAG_BY_ID = "SELECT * FROM "+TABLENAMESPACE_PLACEHOLDER+" WHERE id = ?";
	
	/**
	 * SELECT * FROM --TABLENAMESPACE_PLACEHOLDER--
	 */
	public static String SELECT_ALLFILETAGS = "SELECT * FROM "+TABLENAMESPACE_PLACEHOLDER;
	
	/**
	 * SELECT * FROM --TABLENAMESPACE_PLACEHOLDER-- WHERE fileid = ? AND tag = ?
	 */
	public static String SELECT_FILETAG_BY_VALUE_AND_FILEID = "SELECT * FROM "+TABLENAMESPACE_PLACEHOLDER+" WHERE fileid = ? AND tag = ?";
	
	/**
	 * SELECT * FROM --TABLENAMESPACE_PLACEHOLDER-- WHERE fileid = ?
	 */
	public static String SELECT_ALL_FILETAGS_BY_FILEID = "SELECT * FROM "+TABLENAMESPACE_PLACEHOLDER+" WHERE fileid = ?";
	
	/**
	 * SELECT * FROM --TABLENAMESPACE_PLACEHOLDER-- WHERE tag LIKE ?
	 */
	public static String SELECT_ALL_FILETAGS_BY_PATTERN = "SELECT * FROM "+TABLENAMESPACE_PLACEHOLDER+" WHERE tag LIKE ?";
	
	/**
	 * SELECT * FROM --TABLENAMESPACE_PLACEHOLDER-- WHERE LOWER(tag) LIKE ?
	 */
	public static String SELECT_ALL_FILETAGS_BY_PATTERN_CASE_INSENSITIVE = "SELECT * FROM "+TABLENAMESPACE_PLACEHOLDER+" WHERE LOWER(tag) LIKE ?";
	
	/**
	 * SELECT * FROM --TABLENAMESPACE_PLACEHOLDER-- WHERE fileid = ? AND tag LIKE ?
	 */
	public static String SELECT_ALL_FILETAGS_BY_FILEID_AND_PATTERN = "SELECT * FROM "+TABLENAMESPACE_PLACEHOLDER+" WHERE fileid = ? AND tag LIKE ?";
	
	/**
	 * DELETE FROM --TABLENAMESPACE_PLACEHOLDER-- WHERE id = ?
	 */
	public static String DELETE_FILETAG_BY_ID = "DELETE FROM "+TABLENAMESPACE_PLACEHOLDER+" WHERE id = ?";
	
	
	/**
	 * UPDATE FROM --TABLENAMESPACE_PLACEHOLDER-- SET tag =? WHERE id = ?
	 */
	public static String UPDATE_FILETAG_BY_ID = "UPDATE "+TABLENAMESPACE_PLACEHOLDER+" SET tag =? WHERE id = ?";
	
	/**
	 * INSERT INTO --TABLENAMESPACE_PLACEHOLDER-- (fileid,tag) VALUES (?,?)
	 */
	public static String INSERT_FILETAG = "INSERT INTO "+TABLENAMESPACE_PLACEHOLDER+" (fileid,tag) VALUES (?,?)";

}
