version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: doc-factory-doc
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: doc-factory-extension-demos
    schedule:
      interval: daily
