Variables:

  # It contains the resources full path used to store:
  # - case documents (documents related to the case, available in WorklowUI)
  # - case resources (documents related to the case, not available in WorklowUI)
  # - application resources (files not related to cases) used by others Ivy projects
  # Remarks:
  # #1 If there is no value set, then the {application file area/application name} is used,
  # #2 It is recommended to set the value which is reacheable 
  # even in the ivy Engine Enterprise edition installation, ex under Windows:
  # \\chtitp024\c$\Temp\xivy\caseDocuments
  xivy_addons_resourcesPath: ''

