version: '3.3'
services:
  builder:
    image: axonivy/build-container:read-the-docs-2
    ports:
     - "8000:8000"
    volumes:
     - ".:/doc-factory-doc"
    entrypoint: "make livehtml BASEDIR=/doc-factory-doc"
