name: Release-Build-Dev
run-name: Release-Build-Dev ${{ github.ref_name }}${{ inputs.dryRun && ' (dry run)' || '' }}

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry run mode for release and cleanup
        type: boolean
        required: false
        default: true

permissions:
  contents: read
  actions: read
  packages: write

jobs:
  release:
    uses: axonivy-market/github-workflows/.github/workflows/release-dev.yml@v6
    with:
      dryRun: ${{ inputs.dryRun }}
      javaVersion: 21
    secrets: inherit
