name: Release-Build-Dev

on:
  schedule:
    - cron: '21 21 * * *'
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry run mode for release and cleanup
        type: boolean
        required: false
        default: true

permissions:
  contents: read
  actions: read
  packages: write

jobs:
  release:
    uses: axonivy-market/github-workflows/.github/workflows/release-dev.yml@v6
    with:
      dryRun: ${{ fromJSON(github.event_name == 'schedule' && 'false' || github.event_name == 'workflow_dispatch' && github.event.inputs.dryRun || 'true') }}
      javaVersion: 25
    secrets: inherit
